input {
  file {
    path => "/usr/share/logstash/logs/ndjson/*"           # Path to your NDJSON file
    start_position => "beginning"       # Read file from the beginning
    sincedb_path => "/dev/null"         # Disable sincedb for development
    codec => "json"                     # Parse input as JSON
  }
}

filter {
  # Optional transformations or filtering
  mutate {
    add_field => { "ingested_at" => "%{@timestamp}" } # Add a timestamp field
  }
}

output {
  opensearch {
    hosts => ["http://opensearch-dashboard:9200"]    # OpenSearch endpoint
    user => "admin"                                  # OpenSearch username
password => "Jallafisk1234!!!"                       # OpenSearch password
    index => "ndjson         "                       # OpenSearch index name
    ssl => true                                      # Enable SSL (if required)
    ssl_certificate_verification => false            # Verify certificates
  }
}
