- name: Hunter Workstation Setup Routine
  hosts: localhost
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Setup Hostname
      ansible.builtin.hostname:
        name: huntstation

    - name: Enable and start SSH
      ansible.builtin.service:
        name: sshd
        enabled: true
        state: started

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Install the 'Development tools' package group
      ansible.builtin.dnf:
        name: '@Development tools'
        state: present

    - name: Installing common software
      ansible.builtin.dnf:
        name:
          - git
          - vim
          - yum-utils
          - python3-pip
          - unzip
          - tar
          - bzip2
          - gcc
          - kernel-headers
          - kernel-devel
          - curl
          - wget
          - ruby
          - ruby-devel
          - podman
          - podman-compose

    - name: Enable service podman, and not touch the state
      ansible.builtin.service:
        name: podman
        enabled: yes

    - name: Enable podman socket, and not touch the state
      ansible.builtin.service:
        name: podman.socket
        enabled: yes

    - name: Start service podman, if not started
      ansible.builtin.service:
        name: podman
        state: started

    - name: Start service podman socket, if not started
      ansible.builtin.service:
        name: podman.socket
        state: started
    
    - name: Disable memory paging and swapping performance on the host to improve performance.
      ansible.builtin.command: swapoff -a
      changed_when: true

    - name: Increase the number of memory maps available to OpenSearch.
      ansible.builtin.lineinfile:
        line: vm.max_map_count=262144
        dest: "/etc/sysctl.conf"

    - name: Reload the kernel parameters using sysctl
      ansible.builtin.command: sysctl -p
      changed_when: true

    - name: Adding user hunter
      ansible.builtin.user:
        name: hunter
        password: "$6$wbRe8SmhRl7L89kC$3C0DVYsQOT0rjyTogcltmKZpKBH2poUJBKrj0NEPVnIRX3zR.8r/RbDyrHKFOR6xQebDB5V8XHwjxQpmOdlxK1"
        shell: /bin/bash
        groups: wheel
        append: true

    - name: Starting Podman images
      ansible.builtin.command: podman-compose up -d
      changed_when: true

    - name: Generating systemd file for machine opensearch-node1
      ansible.builtin.command: podman generate systemd --new --files --name opensearch-node1
      changed_when: true

    - name: Generating systemd file for machine opensearch-node2
      ansible.builtin.command: podman generate systemd --new --files --name opensearch-node2
      changed_when: true

    - name: Generating systemd file for machine opensearch-dashboards
      ansible.builtin.command: podman generate systemd --new --files --name opensearch-dashboards
      changed_when: true

    - name: Generating systemd file for machine opensearch-logstash
      ansible.builtin.command: podman generate systemd --new --files --name opensearch-logstash
      changed_when: true

    - name: Stopping machine opensearch-node1
      ansible.builtin.command: podman stop opensearch-node1
      changed_when: true

    - name: Stopping machine opensearch-node2
      ansible.builtin.command: podman stop opensearch-node2
      changed_when: true

    - name: Stopping machine opensearch-dashboards
      ansible.builtin.command: podman stop opensearch-dashboards
      changed_when: true

    - name: Stopping machine opensearch-logstash
      ansible.builtin.command: podman stop opensearch-logstash
      changed_when: true

    - name: Cleaning Podman containers
      ansible.builtin.command: podman rm -a --force
      changed_when: true

    - name: Cleaning Podman volumes
      ansible.builtin.command: podman volume prune --force
      changed_when: true

    - name: Moving service file container-opensearch-dashboards.service
      ansible.builtin.command: mv container-opensearch-dashboards.service /etc/systemd/system/
      changed_when: true

    - name: Moving service file container-opensearch-node1.service
      ansible.builtin.command: mv container-opensearch-node1.service /etc/systemd/system/
      changed_when: true

    - name: Moving service file container-opensearch-node2.service
      ansible.builtin.command: mv container-opensearch-node2.service /etc/systemd/system/
      changed_when: true

    - name: Moving service file container-opensearch-logstash.service
      ansible.builtin.command: mv container-opensearch-logstash.service /etc/systemd/system/
      changed_when: true

    - name: Reloading services
      ansible.builtin.command: systemctl daemon-reload
      changed_when: true

    - name: Reloading service container-opensearch-node1
      ansible.builtin.command: systemctl enable container-opensearch-node1.service
      changed_when: true

    - name: Reloading service container-opensearch-node2
      ansible.builtin.command: systemctl enable container-opensearch-node2.service
      changed_when: true

    - name: Reloading service container-opensearch-dashboards
      ansible.builtin.command: systemctl enable container-opensearch-dashboards.service
      changed_when: true

    - name: Reloading service container-opensearch-logstash
      ansible.builtin.command: systemctl enable container-opensearch-logstash.service
      changed_when: true