- name: Hunter Workstation Setup Routine
  hosts: localhost
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Setup Hostname
      ansible.builtin.hostname:
        name: huntstation

    - name: Enable and start SSH
      ansible.builtin.service:
        name: sshd
        enabled: true
        state: started

    - name: Import OpenSearch PGP Key
      ansible.builtin.rpm_key:
        state: present
        key: https://artifacts.opensearch.org/publickeys/opensearch.pgp

    - name: Add OpenSearch repository
      ansible.builtin.yum_repository:
        name: OpenSearch
        description: OpenSearch reposiotry
        baseurl: https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/opensearch-2.x.repo

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Cleaning Yum
      ansible.builtin.command: yum clean all
      changed_when: true

    - name: Installing software
      ansible.builtin.dnf:
        name:
          - '@Development tools'
          - git
          - vim
          - yum-utils
          - python3-pip
          - unzip
          - tar
          - bzip2
          - gcc
          - kernel-headers
          - kernel-devel
          - curl
          - wget
          - ruby
          - ruby-devel
          - opensearch
          - opensearch-dashboards

    - name: Disable memory paging and swapping performance on the host to improve performance.
      ansible.builtin.command: swapoff -a
      changed_when: true

    - name: Increase the number of memory maps available to OpenSearch.
      ansible.builtin.lineinfile:
        line: vm.max_map_count=262144
        dest: "/etc/sysctl.conf"

    - name: Reload the kernel parameters using sysctl
      ansible.builtin.command: sysctl -p
      changed_when: true

    - name: Adding user hunter
      ansible.builtin.user:
        name: hunter
        password: "$6$wbRe8SmhRl7L89kC$3C0DVYsQOT0rjyTogcltmKZpKBH2poUJBKrj0NEPVnIRX3zR.8r/RbDyrHKFOR6xQebDB5V8XHwjxQpmOdlxK1"
        shell: /bin/bash
        groups: wheel
        append: true

    - name: Creating logstash folder
      ansible.builtin.command: mkdir /usr/share/logstash
      changed_when: true

    - name: Creating logstash logs folder
      ansible.builtin.command: mkdir /usr/share/logstash/logs
      changed_when: true

    - name: Creating logstash ndjson logs folder
      ansible.builtin.command: mkdir /usr/share/logstash/logs/ndjson
      changed_when: true

    - name: Creating logstash logstash.conf file
      ansible.builtin.command: cp logstash.conf /usr/share/logstash/logstash.conf
      changed_when: true

    - name: Enable Opensearch
      ansible.builtin.command: systemctl enable opensearch
      changed_when: true

    - name: Start Opensearch
      ansible.builtin.command: systemctl start opensearch
      changed_when: true
      
    - name: Enable Opensearch Dashboards
      ansible.builtin.command: systemctl enable opensearch-dashboards
      changed_when: true

    - name: Start Opensearch Dashboards
      ansible.builtin.command: systemctl start opensearch-dashboards
      changed_when: true
      

      
  