- name: Hunter Workstation Setup Routine
  hosts: localhost
  become: true
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Setup Hostname
      ansible.builtin.hostname:
        name: hunter

    - name: Installing common software
      ansible.builtin.dnf:
        name:
          - git
          - vim
          - yum-utils
          - python3-pip
          - unzip
          - tar
          - bzip2
          - gcc
          - kernel-headers
          - kernel-devel
          - curl
          - wget
        state: present

    - name: Enable and start SSH
      ansible.builtin.service:
        name: sshd
        enabled: true
        state: started

    - name: Adding user hunter
      ansible.builtin.user:
        name: hunter
        password: "$6$wbRe8SmhRl7L89kC$3C0DVYsQOT0rjyTogcltmKZpKBH2poUJBKrj0NEPVnIRX3zR.8r/RbDyrHKFOR6xQebDB5V8XHwjxQpmOdlxK1"
        shell: /bin/bash
        groups: wheel
        append: true

    - name: Disable memory paging and swapping
      ansible.builtin.command:
        cmd: swapoff -a
      changed_when: true

    - name: Increase the number of memory maps available to OpenSearch
      ansible.builtin.lineinfile:
        line: vm.max_map_count=262144
        dest: "/etc/sysctl.conf"

    - name: Reload kernel parameters using sysctl
      ansible.builtin.command:
        cmd: sysctl -p
      changed_when: true

    - name: OpenSearch - adding repository
      ansible.builtin.get_url:
        url: https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/opensearch-2.x.repo
        dest: /etc/yum.repos.d/opensearch-2.x.repo
        mode: '0644'

    - name: Clean all yum caches
      ansible.builtin.command:
        cmd: yum clean all

    - name: Export OpenSearch initial admin password
      ansible.builtin.shell: |
        export OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin

    - name: Install OpenSearch
      ansible.builtin.command:
        cmd: yum install -y opensearch

    - name: Configure OpenSearch in opensearch.yml
      ansible.builtin.blockinfile:
        path: /etc/opensearch/opensearch.yml
        marker: "# {mark} OpenSearch Configuration"
        block: |
          network.host: 0.0.0.0
          discovery.type: single-node
          plugins.security.disabled: false

    - name: Set initial JVM heap size to 4 GB
      ansible.builtin.lineinfile:
        path: /etc/opensearch/jvm.options
        regexp: '^-Xms\d+[mMgG]'
        line: '-Xms4g'

    - name: Set maximum JVM heap size to 4 GB
      ansible.builtin.lineinfile:
        path: /etc/opensearch/jvm.options
        regexp: '^-Xmx\d+[mMgG]'
        line: '-Xmx4g'

    - name: Ensure OpenSearch certificate directory exists
      ansible.builtin.file:
        path: /etc/opensearch
        state: directory

    - name: Remove demo certificates
      ansible.builtin.shell:
        cmd: rm -f *.pem
        chdir: /etc/opensearch

    - name: Create private key for root certificate
      ansible.builtin.command:
        cmd: openssl genrsa -out /etc/opensearch/root-ca-key.pem 2048

    - name: Create self-signed root certificate
      ansible.builtin.command:
        cmd: openssl req -new -x509 -sha256 -key /etc/opensearch/root-ca-key.pem \
            -subj "/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=ROOT" \
            -out /etc/opensearch/root-ca.pem -days 730

    - name: Enable the OpenSearch service to start on boot
      ansible.builtin.service:
        name: opensearch
        enabled: true

    - name: Start the OpenSearch service
      ansible.builtin.service:
        name: opensearch
        state: started
