apache-pipeline:
  source:
    file:
      path: "/usr/share/data-prepper/logs/access.log"
      record_type: "event"
  processor:
    - grok:
        match:
          message: [ '%{IPV4:client_ip} - - \[%{HTTPDATE:time}\] "%{WORD:http_request_method} %{URIPATH:http_request_uri_path} HTTP/%{NUMBER:http_version}" %{NUMBER:http_response_status_code} %{NUMBER:http_response_body_bytes} "%{GREEDYDATA:http_url}" "%{GREEDYDATA:http_user_agent}"' ]
    - date:
        match:
          - key: "time"
            patterns: ["dd/MMM/yyyy:HH:mm:ss Z"]
        destination: "@timestamp"
    - date:
        from_time_received: true
        destination: "@timestamp_ingested"
  sink:
    - opensearch:
        hosts: [ "https://opensearch-node1:9200" ]
        insecure: true
        username: "admin"
        password: "Opensearch1234!!!!"
        index: "apache-logs"

elastic-ndjson-pipeline:
  source:
    file:
      path: "/opt/predefender/logs/HuntingforDiscovery.ndjson"
      codec:
        ndjson: {}
  processor:
      - select_entries:
          include_keys: [ "_source" ]
      - rename_keys:
          entries:
              - from_key: "_source"
                to_key: "docroot"
  sink:
    # - stdout:
    - opensearch:
        hosts: [ "https://localhost:9200" ]
        insecure: true
        username: "admin"
        password: "Opensearch1234!!!!"
        index: "ndjson-logs-example"
        document_root_key: "docroot"
        dlq_file: /opt/predefender/dlq/dead-entries
          # flush_timeout: 30000
          # bulk_size: 15000
