apache-pipeline:
  source:
    file:
      path: "/usr/share/data-prepper/logs/access.log"
      record_type: "plain"
  processor:
    - grok:
        match: "%{COMMONAPACHELOG}"
  sink:
    - opensearch:
        hosts: [ "https://opensearch-node1:9200" ]
        insecure: true
        username: "admin"
        password: "Opensearch1234!!!!"
        index: "apache-logs"
